version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm install
  pre_build:
    commands:
      - echo Pre-build step...
  build:
    commands:
      - echo Building the project...
      - npm run build || echo "No build script"
  post_build:
    commands:
      - echo Post-build step...
artifacts:
  files:
    - '**/*'
  discard-paths: no
